### ISSUE TITLE
Harvesting can result in multiple outputs

### ISSUE THREAD

**Issue by Arkhorse** [No3371/TLD-QoL#1]
Ive noticed harvesting saplings and picking up rope can result in 8x the amount added to the inventory. This can be even more (most I have seen is 37x)

To Replicate:
Have mod installed
Harvest any sapling

**Comment by No3371** [comment]
Whoa! 37 is pretty wild!
This is a very serious bug, thanks for the report. I'll deal with it asap.

**Comment by No3371** [comment]
Hey, I believe I got it fixed, for now, FastPick only works for items on the ground (means not from Harvestables/CookingPot/FishingHole/Containers).

Please test it out and tell me the result, because my precious save somehow get killed in 3 seconds by a wolf while fully equipped, and my new save doesn't even have a Hatchet 😭 

Along with this fix, a bunch of features are added, so the Readme needs a update again, that will take some time, so in the meantime, please use this [unreleased version](https://wormhole.app/zPo2L#d45JO7xrZtIi9-haxh6ZCg) if you need it now.

Tip about the new features: try out the Alternative Interact key (I set it to F, it's so good) and do A/D scroll, everywhere.

**Comment by No3371** [comment]
1.3.0 is released. Please also check Readme.
